name: "Hello World!"
description: "Greet the world"
author: "vathsala"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"
